Repository mr-professor4569/Data_Structures, pull requests merged in 2020-10, with the labels that each got.

#13 Recursive Problem Added
  Recursive Problem 1.cpp
Labels: Hacktoberfest2020, enhancement, good first issue

#14 #8 Task Done
  Sort by freq.cpp
Labels: Hacktoberfest2020, enhancement, good first issue

#18 Kadane's Algo added
  Kadane's .cpp
Labels: Hacktoberfest2020, enhancement, good first issue, hacktoberfest, hacktoberfest-accepted

#19 Largest Subarray sum added
  Largest sumSub array.cpp
Labels: Hacktoberfest2020, enhancement, hacktoberfest, hacktoberfest-accepted

#21 Max circular subarray sum added
  Max circular subarray sum.cpp
Labels: Hacktoberfest2020, enhancement, hacktoberfest, hacktoberfest-accepted

#25 Rearrange pos and neg in an array
  Rearrange pos and neg in an array.cpp
Labels: Hacktoberfest2020, hacktoberfest, hacktoberfest-accepted

#22 NumberOfIslands.cpp
  NumberOfIslands.cpp
Labels: Hacktoberfest2020, good first issue, hacktoberfest, hacktoberfest-accepted

#26 Updating for proper transfer for rods
  Recursive Problem 1.cpp
Labels: Hacktoberfest2020, hacktoberfest, hacktoberfest-accepted

#28 no. of pairs with sum equal to a given number
  Counting pairs in an array whose sum is equal to a given number
Labels: Hacktoberfest2020, hacktoberfest, hacktoberfest-accepted

#32 Making code more compatible
  selection sort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#31 Create 0-1 knapsack
  0-1 knapsack
Labels: hacktoberfest, hacktoberfest-accepted

#29 Program to find max product subarray
  Find MAX product subarray
Labels: hacktoberfest, hacktoberfest-accepted

#30 Bubble Sort Using Array
  Bubble Sort Using Array
Labels: hacktoberfest, hacktoberfest-accepted

#33 added binary search java file
  BinarySearch.java
Labels: hacktoberfest, hacktoberfest-accepted

#34 LinkedListUsingC++
  LinkedList
Labels: good first issue, hacktoberfest, hacktoberfest-accepted
